skynet118/blog/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

#include("blog")
app_name = 'blog'


urlpatterns = [
        # 
        path("register/", views.registerPage, name = "register"),
        path("login/", views.loginPage, name = "login-page"),
        path("logout/", views.logoutUser, name = "logout"),
        path(
            "password_reset/", 
            auth_views.PasswordResetView.as_view(
                template_name="blog/password_reset_form.html",
                email_template_name="blog/password_reset_email.html",
                subject_template_name="blog/password_reset_subject.txt",
                success_url = reverse_lazy('blog:password_reset_done') 
                ), 
            name = "password_reset"),

        path(
            "password_reset/done/",
            auth_views.PasswordResetDoneView.as_view(
                template_name="blog/password_reset_done.html"
                ),
            name = "password_reset_done"),

        path(
            "reset/<uidb64>/<token>/",
            auth_views.PasswordResetConfirmView.as_view(
                template_name="blog/password_reset_confirm.html",
                success_url = reverse_lazy('blog:password_reset_complete') 
                ),
            name = "password_reset_confirm"),
        path(
            "password_reset_complete/", 
            auth_views.PasswordResetCompleteView.as_view(
                template_name="blog/password_reset_complete.html"
                ), 
            name = "password_reset_complete"),

        path("restricted/", views.restricted_view, name = "restricted"),

        path("", views.index, name = "index"),
        path("contact/", views.contact_view, name = "contact"),
        path("contacts/", views.contacts_view, name = "contacts"),
        path("contact_create/", views.contact_create, name = "contact-create"),
        path("client_contact/", views.client_contact_view, name = "client-contact"),

        path("profile_create/", views.profile_create, name = "profile-create"),
        path("profile/<int:id>", views.profile_view, name = "profile"),
        path("profile_update/<int:id>", views.profile_update, name = "profile-update"),

        path("portfolio_create/", views.portfolio_create, name = "portfolio-create"),
        path("portfolios/", views.portfolios_view, name = "portfolios"),
        path("portfolio/<int:id>", views.portfolio_view, name = "portfolio"),
        path("portfolio_update/<int:pk>", views.portfolio_update, name = "portfolio-update"),

        path("comment/", views.CommentView.as_view(), name = "comments"),
        path("comment/<slug:slug>", views.CommentDetailView.as_view(), name = "comment-detail"),
        ]

skynet118/courses/urls.py
from django.urls import path, include
from . import views

#include("blog")
app_name = 'courses'


urlpatterns = [
        path("", views.index, name = "index_course"),
        path("course_packages/<int:fk>", views.course_package_view, name = "course_packages"),
        path("course/<int:id>", views.course_view, name="course_view"),
        path("create_course/", views.create_course, name = "create_course"),
        path("update_course/<int:pk>", views.update_course, name = "update_course"),
        path("delete_course/<int:pk>", views.delete_course, name = "delete_course"),
        #path("delete/", views.create_course, name = "create"),
        path("create_package/", views.create_package, name = "create_package"),
        path("update_package/<str:pk>", views.update_package, name = "update_package"),
        path("delete_package/<str:pk>", views.delete_package, name = "delete_package"),
    ]

skynet118/payments/urls.py
from django.urls import path, include

from . import views

app_name = "payments"

urlpatterns = [
        path("checkout/<int:pk>/<str:name>/", views.checkout, name="checkout"),
        path("checkout-trial/<int:id>/", views.checkout_trial, name="checkout-trial"),
        path("success/<str:name>/<str:idpay>", views.payment_complete,  name="success"),
        path("cart/", views.cart,  name="cart"),
        ]

skynet118/skynet118/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
        path('i18n/', include('django.conf.urls.i18n')),
        path('admin/', admin.site.urls),
        path('ckdeditor/', include('ckeditor_uploader.urls')),

        #path('', include('frontend.urls')),
        path('', include("blog.urls")),
        path('student/', include("student.urls")),
        path('payments/', include("payments.urls")),
        path('courses/', include("courses.urls")),
        ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skynet118/courses/models.py
from django.db import models
# Create your models here.

class Course(models.Model):
    course_name = models.CharField(max_length=200)
    date_pub = models.DateTimeField("Date Published")
    price = models.FloatField(default=0)
    nro_lessons = models.IntegerField()
    nro_tests = models.IntegerField()
    details = models.JSONField(default=dict)
    description = models.CharField(max_length=500, default="Description")
    image = models.ImageField(null=True, blank=True)
    topics = models.JSONField(default=dict)

    def __str__(self):
        return self.course_name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Package(models.Model):
    course_package = models.ForeignKey(Course,on_delete=models.CASCADE,related_name='course_package', null=True)
    package_name = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    nro_lessons = models.IntegerField()
    comment = models.CharField(max_length=500)
    time = models.IntegerField()
    
    def __str__(self):
        return self.package_name


class Comment(models.Model):
    comment = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=120)
    email = models.EmailField(max_length=120)
    body = models.TextField(max_length=300)
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)

skynet118/courses/forms.py
from .models import Comment, Course, Package 
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

class PackageForm(forms.ModelForm):
    class Meta:
        model = Package
        fields = '__all__'

skynet118/courses/views.py
from django.shortcuts import render, redirect
from .forms import CommentForm, CourseForm, PackageForm
from django.http import HttpResponse
from .models import Course, Package
from django.shortcuts import render, get_object_or_404
from django.contrib import messages

from blog.decorators import allowed_users

# Create your views here.

def index(request):
    courses = Course.objects.all()
    context = {'courses': courses}
    return render(request , 'courses/index_courses.html', context)


def course_package_view(request, fk):
    course = Course.objects.get(id=fk)
    package = Package.objects.all().filter(course_package=fk)
    context = {'package': package, 'course': course }
    return render(request, 'courses/course_package.html', context)


@allowed_users(allowed_roles=['admin', 'teachers'])
def create_course(request):
    course = CourseForm()
    if(request.method == "POST"):
        course = CourseForm(request.POST, request.FILES)
        if(course.is_valid()):
            course.save()
    context = {'course': course}
    return render(request, 'courses/create_course.html', context)

def course_view(request, id):
    course = Course.objects.get(id=id)
    context = {
        "course": course
            }
    return render(request, 'courses/course_view.html', context) 

@allowed_users(allowed_roles=['admin', 'teachers'])
def update_course(request, pk):
    course = Course.objects.get(id=pk)
    form = CourseForm(instance=course)
    if(request.method == "POST"):
        form = CourseForm(request.POST, instance=course)
        if(form.is_valid()):
            form.save()
            return redirect("/courses/")
    context = {'form': form}
    return render(request, 'courses/update_course.html', context)


@allowed_users(allowed_roles=['admin', 'teachers'])
def delete_course(request, pk):
    course = Course.objects.get(id=pk)
    if(request.method == "POST"):
        package.delete()
        return redirect("/courses/")

    context = {"item": course}
    return render(request, 'courses/delete_course.html', context)


def post_detail(request, slug):
    template_name = 'post_detail.html'
    course = get_object_or_404(Course, slug=slug)
    comments = course.comments.filter(active=True)
    new_comment = None
    
    if(request.method == 'POST'):
        comment_form = CommentForm(data=request.POST)
        if(comment_form.is_valid()):
                new_comment = comment_form.save(commit=False)
                new_comment.course = course 
                new_comment.save()
    else:
        comment_form = CommentForm()

    context = { 
            'course':course,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form
            }

    return render(request, template_name, context)


@allowed_users(allowed_roles=['admin', 'teachers'])
def create_package(request):
    form = PackageForm()
    if(request.method == "POST"):
        form = PackageForm(request.POST, request.FILES)
        if(form.is_valid()):
            form.save()
            return redirect('/courses/')

    context = {'form': form}
    return render(request, 'courses/create_package.html', context)


@allowed_users(allowed_roles=['admin', 'teachers'])
def update_package(request, pk):
    package = Package.objects.get(id=pk)
    form = PackageForm(instance=package)
    if(request.method == "POST"):
        form = PackageForm(request.POST, instance=package)
        if(form.is_valid()):
            form.save()
            return redirect("/courses/")
    context = {'form': form}
    return render(request, 'courses/update_package.html', context)


@allowed_users(allowed_roles=['admin', 'teachers'])
def delete_package(request, pk):
    package = Package.objects.get(id=pk)
    if(request.method == "POST"):
        package.delete()
        return redirect("/courses/")

    context = {"item": package}
    return render(request, 'courses/delete.html', context)

skynet118/courses/templates/courses/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static "blog/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "courses/courses_style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "blog/media.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "courses/media.css" %}">
    <link rel="icon" type="image/gif" href="{% static "blog/images/favicon.ico" %}">
    <title></title>
</head>
<body>
    {% include 'blog/menu_var.html' %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    {% include 'blog/footer.html' %}
</body>
</html>

skynet118/courses/templates/courses/course_package.html
{% extends 'courses/base.html' %}
{% block content %}
{% load static %}

<section class="trial-lesson">
    <div class="trial-lesson-details">
        <h2>Try out a lesson</h2>
        <p>Course: {{course.course_name}}</p>
        <p>Price: ${{ course.price }}</p>
        <a class= "link-buy" href="{% url 'payments:checkout-trial' course.id %}">
            <strong>Try it out!</strong>
        </a>
        <p><small>
            ** the trial lesson is through Zoom app
            you can download the app here.
            </small></p>

    </div>
</section>
<section class="title-course">
    <h1>{{ course.course_name }}</h1>
    <p>All packages available</p>
</section>
<article class="list-price-available">
    {% for elem in package %}
    <div class="price">
        <ul>
            <li class="package-name {{elem.package_name}}">
                <strong>{{ elem.package_name }}
                </strong>
            </li>
            <li>Number of lessons: {{ elem.nro_lessons }}</li>
            <li>Duration: {{ elem.time }} minutes</li>
            <li class="price-course">
                <p>Total cost: <span>${{ elem.price }}</span></p>
                <p>{{ elem.comment }}</p>
            </li>
            <li>
                <a class= "link-buy" href="{% url 'payments:checkout' pk=elem.course_package.id name=elem.package_name %}">
                    <strong>Buy it</strong>
                </a>
            </li>
        </ul>
    </div>
    {% endfor %}
</article>
{% endblock %}

skynet118/courses/templates/courses/course_view.html
{% extends 'courses/base.html' %}
{%  block content %}
<section class="course-view">
    <fieldset>
        <legend>{{course.course_name}}</legend>
        <div class="course-image">
            <img src="{{course.imageURL}}" alt="">
        </div>
        <p>Course name: {{course.course_name}}</p>
        <p>Number of lesson: {{course.nro_lessons}}</p>
        <p>Price per lesson: {{course.price}}</p>
        <p>Number of tests: {{course.nro_tests}}</p>
        <label for="">Why we should choose {{course.course_name}}?</label>
        <ul>
            {% for key, detail in course.details.items %}
            <li>{{detail}}</li>
            {% endfor %}
        </ul>
        <p>Description: {{course.description}}</p>
        <label for="">Topics in this course: </label> 
        <ul>
            {% for key, topic in course.topics.items %}
                <li>{{topic}}</li>
            {% endfor %}
        </ul>

        {% if user.is_active and user.is_staff %}
            <a href="{% url 'courses:update_course' pk=course.pk  %}">Update Course</a>
        {% endif %}
        <a class="pricing" href="{% url 'courses:course_packages' fk=course.id %}">Pricing</a>
    </fieldset>
</section>
{% endblock content %}

skynet118/courses/templates/courses/create_course.html
{% extends "courses/base.html" %}
{% load static %}
{% block content %}
<section>
    <form action="" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Create a course</legend>
            <section>
                {{ course.course_name }}
            </section>
            <section>
                {{ course.date_pub }}
            </section>
            <section>
                {{ course.price }}
            </section>
            <section>
                {{ course.nro_lessons }}
            </section>
            <section>
                {{ course.nro_tests }}
            </section>
                <div class="details-course">
                    <p>Course Details:</p>
                    <ul>
                    </ul>
                </div>
                {{ course.details }}
                <div class="buttons-course">
                </div>
            <section>
                {{ course.description }}
            </section>
            <section>
                {{ course.image }}
            </section>
            <section>
                {{ course.topics }}
            </section>
        </fieldset>
        <div class="btns-create-course">
            <button type="submit">Create</button>
            <button type="button">Cancel</button>
        </div>
        {% for error in course.errors %}
            <p>{{error}} is required</p>
        {% endfor %}
    </form>
</section>
<script src="{% static 'courses/js/create_course.js' %}"></script>
{% endblock content %}

skynet118/courses/templates/courses/create_package.html
{% extends "courses/base.html" %}
{% block content %}

<section class="create-package-form">
    <form action="" method="POST">
        {% csrf_token  %}
        <h1>Create a new package:</h1>
        <fieldset>
            <legend>Fill the form</legend>
            <section>
            {{ form.course_package}}
            </section>
            <section>
                {{form.package_name }}
            </section>
            <section>
                {{ form.price }}
            </section>
            <section>
                {{ form.nro_lessons }}
            </section>
            <section>
                {{ form.comment }}
            </section>
            <section>
                {{ form.time }}
            </section>
        </fieldset>
        <section class="btns-packages">
            <button id="btn-create-package" type="submit">Send</button>
            <button id="btn-cancel-create" type="button" onclick="backHome()">Cancel</button>
        </section>
    </form>
</section>
<script>
    let backHome = () => window.location.replace('/courses/');

    let id_package_name = document.getElementById('id_package_name');
    id_package_name.placeholder = " Package name"

    let id_price = document.getElementById('id_price');
    id_price.placeholder = " price"

    let id_nro_lessons = document.getElementById('id_nro_lessons');
    id_nro_lessons.placeholder = " number of lessons"

    let id_comment = document.getElementById('id_comment');
    id_comment.placeholder = " Comments"

    let id_time = document.getElementById('id_time');
    id_time.placeholder = " time per lesson"
</script>
{% endblock content %}

skynet118/courses/templates/courses/delete.html
{% extends "courses/base.html" %}
{% block content %}


<p>Are you sure you want to delete "{{item}}"?</p>
<form action="{% url 'courses:delete_package' item.id %}" method="POST">
    {% csrf_token  %}
    <a href="{% url 'courses:index_course' %}">Cancel</a>
    <input type="submit" name="confirm" value="confirm"/>
</form>


{% endblock content %}

skynet118/courses/templates/courses/index_courses.html
{% extends 'courses/base.html' %}
{% block content %}
{% load static %}

<h1>All courses available</h1>
<section class="course-description">
    {% if user.is_authenticated and user.is_staff %}
    <div class="create-new-course">
        <a href="{% url 'courses:create_course' %}">Create a new course</a>
    </div>
    {% endif %}
    {% for course in courses %}
    <fieldset>
        <legend>{{course.course_name}}</legend>
        <img id ="img-course" src="{{ course.image.url }}" width="240" height="240" alt="python-course">
        <p>{{ course.description }}</p>
        <p>and Why {{course.course_name }}?...</p>
        <ul>
            {% for key, details in course.details.items %}
            <li>{{details}}</li>
            {% endfor %}
        </ul>
        <aside>
            <p>More about <a href="{% url 'courses:course_view' course.id %}"><strong>{{course.course_name}}</strong></a></p>
        </aside>
        <a class="pricing" href="{% url 'courses:course_packages' fk=course.id %}">Pricing</a>
    </fieldset>
    {% endfor %}
</section>
{% endblock content %}

skynet118/courses/templates/courses/update_course.html
{% extends 'courses/base.html' %}
{% load static %}
{% block content %}
<section class="course_update_form">
    <fieldset>
        <legend>Updating {{form.course_name.value}} Course</legend>
        <form method="POST">{% csrf_token %}
            <section>
                {{form.course_name}}
            </section>
            <section>
                {{form.date_pub}}
            </section>
            <section>
                {{form.price}}
            </section>
            <section>
                {{form.nro_lessons}}
            </section>
            <section>
                {{form.nro_tests}}
            </section>
            <section>
                <div id="details_updated">
                    <p>previous details</p>
                    <ul id="previousDetails"></ul>
                    <ul id="detailsAdded"></ul>
                    <span id="detailButtons"></span>
                    <button 
                        id="modifyButton" 
                        type="button" 
                        onclick="modifyDetails()">
                        Modify details
                    </button>
                </div>
                {{form.details}}
            </section>
            <section>
                {{form.description}}
            </section>
            <section>

                <div id="previous_img">
                    {{form.image}}
                    <p>Previous image:</p>
                    <img width="120" height="120">
                </div>
                <div id="new_img">
                    <p>New image:</p>
                    <img src="" alt="">
                </div>
            </section>
            <section>
                <div class="topics_updated">
                    <label for="">Previous topics:</label>
                    <ul id="previousTopics"></ul>
                    <label for="">Topics updated:</label>
                    <ul id="topicsAdded"></ul>
                    <span id="topicsButtons">
                    </span>
                    <button 
                        id="modifyButton2" 
                        type="button" 
                        onclick="modifyTopics()">
                        Modify topics
                    </button>
                </div>
                {{form.topics}}
            </section>
            <input id="updateButton" type="submit" value="Update">
        </form>
    </fieldset>
</section>
<script src="{% static '/courses/js/update_course.js' %}"></script>
{% endblock content %}

skynet118/courses/templates/courses/update_package.html
{% extends "courses/base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form }} 
    <button type="submit">Update</button>

</form>


{% endblock content %}