skynet118/blog/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

#include("blog")
app_name = 'blog'


urlpatterns = [
        # 
        path("register/", views.registerPage, name = "register"),
        path("login/", views.loginPage, name = "login-page"),
        path("logout/", views.logoutUser, name = "logout"),
        path(
            "password_reset/", 
            auth_views.PasswordResetView.as_view(
                template_name="blog/password_reset_form.html",
                email_template_name="blog/password_reset_email.html",
                subject_template_name="blog/password_reset_subject.txt",
                success_url = reverse_lazy('blog:password_reset_done') 
                ), 
            name = "password_reset"),

        path(
            "password_reset/done/",
            auth_views.PasswordResetDoneView.as_view(
                template_name="blog/password_reset_done.html"
                ),
            name = "password_reset_done"),

        path(
            "reset/<uidb64>/<token>/",
            auth_views.PasswordResetConfirmView.as_view(
                template_name="blog/password_reset_confirm.html",
                success_url = reverse_lazy('blog:password_reset_complete') 
                ),
            name = "password_reset_confirm"),
        path(
            "password_reset_complete/", 
            auth_views.PasswordResetCompleteView.as_view(
                template_name="blog/password_reset_complete.html"
                ), 
            name = "password_reset_complete"),

        path("restricted/", views.restricted_view, name = "restricted"),

        path("", views.index, name = "index"),
        path("contact/", views.contact_view, name = "contact"),
        path("contacts/", views.contacts_view, name = "contacts"),
        path("contact_create/", views.contact_create, name = "contact-create"),
        path("client_contact/", views.client_contact_view, name = "client-contact"),

        path("profile_create/", views.profile_create, name = "profile-create"),
        path("profile/<int:id>", views.profile_view, name = "profile"),
        path("profile_update/<int:id>", views.profile_update, name = "profile-update"),

        path("portfolio_create/", views.portfolio_create, name = "portfolio-create"),
        path("portfolios/", views.portfolios_view, name = "portfolios"),
        path("portfolio/<int:id>", views.portfolio_view, name = "portfolio"),
        path("portfolio_update/<int:pk>", views.portfolio_update, name = "portfolio-update"),

        path("comment/", views.CommentView.as_view(), name = "comments"),
        path("comment/<slug:slug>", views.CommentDetailView.as_view(), name = "comment-detail"),
        ]

skynet118/courses/urls.py
from django.urls import path, include
from . import views

#include("blog")
app_name = 'courses'


urlpatterns = [
        path("", views.index, name = "index_course"),
        path("course_packages/<int:fk>", views.course_package_view, name = "course_packages"),
        path("course/<int:id>", views.course_view, name="course_view"),
        path("create_course/", views.create_course, name = "create_course"),
        path("update_course/<int:pk>", views.update_course, name = "update_course"),
        path("delete_course/<int:pk>", views.delete_course, name = "delete_course"),
        #path("delete/", views.create_course, name = "create"),
        path("create_package/", views.create_package, name = "create_package"),
        path("update_package/<str:pk>", views.update_package, name = "update_package"),
        path("delete_package/<str:pk>", views.delete_package, name = "delete_package"),
    ]

skynet118/skynet118/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
        path('i18n/', include('django.conf.urls.i18n')),
        path('admin/', admin.site.urls),
        path('ckdeditor/', include('ckeditor_uploader.urls')),

        #path('', include('frontend.urls')),
        path('', include("blog.urls")),
        path('student/', include("student.urls")),
        path('payments/', include("payments.urls")),
        path('courses/', include("courses.urls")),
        ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skynet118/student/urls.py
from django.urls import path, include
from . import views

#include("blog")
app_name = 'student'


urlpatterns = [
        path("calendar/<str:student>", views.calendar, name = "calendar"),
        path("my-courses/<str:usr>", views.my_courses, name = "my-courses"),
        ]

skynet118/courses/models.py
from django.db import models
# Create your models here.

class Course(models.Model):
    course_name = models.CharField(max_length=200)
    date_pub = models.DateTimeField("Date Published")
    price = models.FloatField(default=0)
    nro_lessons = models.IntegerField()
    nro_tests = models.IntegerField()
    details = models.JSONField(default=dict)
    description = models.CharField(max_length=500, default="Description")
    image = models.ImageField(null=True, blank=True)
    topics = models.JSONField(default=dict)

    def __str__(self):
        return self.course_name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Package(models.Model):
    course_package = models.ForeignKey(Course,on_delete=models.CASCADE,related_name='course_package', null=True)
    package_name = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    nro_lessons = models.IntegerField()
    comment = models.CharField(max_length=500)
    time = models.IntegerField()
    
    def __str__(self):
        return self.package_name


class Comment(models.Model):
    comment = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=120)
    email = models.EmailField(max_length=120)
    body = models.TextField(max_length=300)
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)

skynet118/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import (
        UserProfile,
        Portfolio,
        Comment,
        ClientContact
        )

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'


class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio 
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = '__all__'

class ClientContactForm(forms.ModelForm):
    class Meta:
        model = ClientContact
        fields = '__all__'
# Models for the user registration

class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        #fields = '__all__' # not recommended 
        fields = ['username','first_name', 'last_name', 'email', 'password1', 'password2'] 

skynet118/blog/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
#from django.template import loader
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from django import forms
#importing for user
from django.contrib.auth.models import User, Group

from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.utils.translation import gettext as _

from .decorators import (
        unauthenticated_user, 
        portfolio_created, 
        allowed_users, 
        admin_only,
        profile_created
        )

from .forms import (
        UserProfileForm,
        PortfolioForm,
        CommentForm,
        RegisterUserForm,
        ClientContactForm
        )

# importing models 
from courses.models import Course

from .models import (
            UserProfile,
            Comment,
            Portfolio
        )

# importing forms

from django.contrib.auth.forms import UserCreationForm

# importing serializers 

from .serializers import  ClientContactSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view


# Create your views here.

def index(request):
    courses = Course.objects.all().order_by('id')
    if(request.method == "POST"):
        data = request.body.decode('utf-8')
    context = {
            "courses": courses
            }
    return render(request, 'blog/index.html', context) 

##################################################

def contact_view(request):
    if(request.user.is_authenticated):
        user = User.objects.get(username=request.user) 
        context = {
                'user': user
                }
    return render(request, 'blog/contact.html', context)

def contacts_view(request):
    users = User.objects.all() 
    context = {
            'users': users
            }
    return render(request, 'blog/contacts.html', context)


def contact_create(request):
    if(request.method == 'POST'):
        contact = ContactProfileForm(request.POST)
        print(request.body)
        if(contact.is_valid()):
            contact.save()
            return redirect('/')
        context = {'contact': contact}
        return render(request, 'blog/contact_create.html', context)

def contact_update(request, pk):
    pass

def contact_delete(request, pk):
    pass

##################################################

def portfolios_view(request):
    portfolios = Portfolio.objects.all()
    context = {'portfolios': portfolios}
    return render(request, 'blog/portfolios.html', context)

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


def portfolio_view(request, id):
    portfolio_exists = Portfolio.objects.filter(user=id).exists()
    if(portfolio_exists):
        #portfolio = Portfolio.objects.get(user=request.user)
        portfolio = Portfolio.objects.get(user=id)
        context = {'portfolio': portfolio}
        return render(request, 'blog/portfolio.html', context)
    else:
        return redirect('/portfolio_create/')

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)

@portfolio_created
@allowed_users(allowed_roles=['admin', 'teacher'])
def portfolio_create(request):
    portfolio = PortfolioForm()
    if(request.method == 'POST'):
        portfolio = PortfolioForm(request.POST, request.FILES)
        if(portfolio.is_valid()):
            portfolio.save()
            portfolio_name = portfolio.cleaned_data.get('name')
            messages.success(request, "The portfolio was successful created for " + portfolio_name)
            messages.error(request, "Here is an error")
            return redirect('/')

    context = {'portfolio': portfolio }
    return render(request, 'blog/portfolio_create.html', context)

@allowed_users(allowed_roles=['admin', 'teacher'])
def portfolio_update(request, pk):
    portfolio = Portfolio.objects.get(id=pk)
    form = PortfolioForm(instance=portfolio)
    if(request.method == "POST"):
        form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
        if(form.is_valid()):
            img_path = portfolio.image.path 
            if(os.path.exists(img_path)):
                os.remove(img_path)
            form.save()
            return redirect(f"/portfolio/{request.user.id}")
    context = {'form': form}
    return render(request, 'blog/portfolio_update.html', context)

##################################################

class CommentView(generic.ListView):
    model = Comment 
    template_name = "blog/comment.html"
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class CommentDetailView(generic.DetailView):
    model = Comment
    template_name = "blog/comment_detail.html"

##################################################

@unauthenticated_user
def registerPage(request):
    form = RegisterUserForm()
    if(request.method == "POST"):
        form = RegisterUserForm(request.POST)
        if(form.is_valid()):
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            email_exists = User.objects.filter(email=email).exists()
            if(email_exists):
                messages.error(request, f"The email: {email} is already in use")
                return redirect("/register/")
            user = form.save()
            group = Group.objects.get(name='customer')
            user.groups.add(group)
            messages.success(request, "The account was successful created for " + username)

            return redirect("/login/")

    context = {'form': form}
    return render(request, 'blog/register.html', context)

##################################################

@allowed_users(allowed_roles=['admin', 'teacher', 'student'])
def profile_create(request):
    profile = UserProfileForm()
    if(request.method == "POST"):
        profile = UserProfileForm(request.POST, request.FILES)
        if(profile.is_valid()):
            profile.save()
            return redirect("/") 
    context = {"profile": profile}
    return render(request, 'blog/profile_create.html', context)


def profile_view(request, id):
    profile_exists = UserProfile.objects.filter(user=id).exists()
    if(profile_exists):
        profile = UserProfile.objects.get(user=request.user)
        context = {'profile': profile}
        return render(request, 'blog/profile.html', context)
    else:
        return redirect('/profile_create/')


def profile_update(request, id):
    profile = UserProfile.objects.get(id=id)
    form = UserProfileForm(instance=profile)
    if(request.method == "POST"):
        form = UserProfileForm(request.POST, request.FILES , instance=profile)
        if(form.is_valid()):
            img_path = profile.avatar.path 
            if(os.path.exists(img_path)):
                os.remove(img_path)
            form.save()
            return redirect(f"/profile/{request.user.id}")
    context = {'form': form}
    return render(request, 'blog/profile_update.html', context)





##################################################

@unauthenticated_user
def loginPage(request):
    if(request.method == "POST"):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if(user is not None):
            login(request, user)
            return redirect("/")
        else:
            messages.info(request, "The username or password is incorrect")
    context = {}
    return render(request, 'blog/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('/')

def restricted_view(request):
    user = request.user 
    context = {
            'user': user
            }
    return render(request, 'blog/restricted_page.html', context)

@api_view(['POST'])
def client_contact_view(request):
    client_contact = ClientContactSerializer(data=request.data)
    print(client_contact.is_valid())

    if(client_contact.is_valid()):
        client_contact.save()
        return Response(client_contact.data)
    else:
        print(client_contact.errors)
        return Response({'errors': client_contact.errors}, status=400)

skynet118/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% block title-header %}Contact{% endblock title-header %}
{% block content %}
    <p>{{ user }}</p> 
{% endblock %}

skynet118/blog/templates/blog/contact_create.html
{% extends 'blog/base.html' %}
{% block content %}
<form action="" method='POST'>
    {% csrf_token %}
    <label for="">Name:</label>
    {{ contact.name }}
    <label for="">Email:</label>
    {{ contact.email }}
    <label for="">Message:</label>
    {{ contact.message }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

skynet118/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title-header %}Skynet118{% endblock title-header %}
{% block description %}
    Do you need coding help with algorithms or programming itself? or maybe some challenge that you want to overcome
or just you want to become a better developer?
We're a team of young developers and designers with years of expertise, we really want to share our experience and knowledge
{% endblock description %}
{% block content %}
{% load static %}
{% load i18n %}
<div class="header-description-kids">
    <div class="description-kids">
        <section class="description-kids-title">
            <h1>let's build the future of our kids together!</h1>
        </section>
        <section class="description-kids-text">
            <p>We are a global online coding school for kids aged 8-17 years</p>
        </section>
        <section class="benefits">
            <h3>What are the Benefits of our school?</h3>
            <ul>
                <li>We show how to productively spend time at the computer</li>
                <li>Pick courses based on your child's level and interests</li>
                <li>we provide individual lessons</li>
                <li>Teachers with industry experience</li>
                <li>we explain programming with simple words</li>
                <li>we are flexible with your schedule</li>
                <li>We teach your child to program and distract from games and YouTube</li>
            </ul>
        </section>
        <section class="kids-achievements">
            <h3>
                Your child will be fully engaged with our programming lessons from the first lesson
            </h3>
            <div class="achievement-container">
                <div class="achievement">
                    <img src="{% static 'blog/images/coding.png' %}" alt="">
                    <p>Your child will write his first program or website</p>
                </div>
                <div class="achievement">
                    <img src="{% static 'blog/images/motherboard.png' %}" alt="">
                    <p>You will see how your child improve his programming skills</p>
                </div>
                <div class="achievement">
                    <img src="{% static 'blog/images/mathematics.png' %}" alt="">
                    <p>Your child will see that programming is much more interesting that playing all day</p>
                </div>
            </div>
        </section>
    </div>
    <div class="trial-lesson">
        {% include 'blog/contact_form.html' %}
    </div>

    {% include 'blog/slides.html' %} 
</div>
<div class="header-description">
    <div class="left-header">
        <p>{% trans 'Do you need coding help with algorithms or programming itself? or maybe some challenge that you want to overcome, or just you want to become a better developer?' %}</p> 
        <img src="{% static 'blog/images/linux_penguin.png' %}" alt="penguin linux">
    </div>
    <div class="right-header">
        <img class="logo-header" src="{% static "blog/images/nico.png" %}">
        <p>{% trans 'Do not waste time searching hours. Here you will find classes from basic level to advanced in programming.' %}</p>
    </div>
    <strong class="header-link"><a href="{% url 'blog:portfolios' %}">{% trans 'Read more!' %}</a></strong> 
</div>
<hr>
<div class="about-us">
  <div class="world-map">
    <h2>Our students around the world</h2>
    <div id="world-container">
        <img id="world-map-img" src="{% static 'blog/images/world.svg' %}" alt="">
    </div>
    <div class="countries">
        <ul>
        </ul>
    </div>
  </div>
  <h2>{% trans 'About us' %}</h2>
  <p>{% trans "We're a team of young developers and designers with years of expertise, we really want to share our experience and knowledge  . . . " %}<a href="{% url 'blog:portfolios' %}">{% trans 'continue.' %}</a></p>
</div>

{% endblock content %}

skynet118/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title-header %}Login{% endblock title-header %}
{% block content %}
<section class="login-account">
    <h1>Start Learning!</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <section>
            <input type="text" name="username" id="login_user" placeholder="  User Name">
        </section>
        <section>
            <input type="password" name="password" id="login_password" placeholder= "  Password">
        </section>

        <input type="submit" value="Log in" id="login">
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
        <p style="font-size: 18px; color: grey;" >Don't have an account? <a href="{% url 'blog:register' %}"><strong>Sign up</strong></a></p>
        <a style="font-size: 14px; color: grey;" href="{% url 'blog:password_reset' %}"><strong>You forgot your password?</strong></a></p>
    </form>
</section>
{% endblock %}

skynet118/blog/templates/blog/menu_var.html
{% load static %}
{% load i18n %}
<header class="menu">
    <div class="logo">
        <div class="logo-img">
            <img src="{% static 'blog/images/nico.png' %}">
        </div>
        <p>Skynet118</p>
    </div>
    <div class="search-field">
        <form class="search-box" action="" method="GET">
            <input type="text" name="text" class="search-txt" placeholder="{% trans 'Search here' %}">
            <input type="submit" name="submit" class="search-btn" value="Find">
        </form>
    </div>
    <nav class="links">
        <ul> 
            <li><a href="{% url 'blog:index' %}">{% trans 'Home' %}</a></li>
            <li><a href="{% url 'courses:index_course' %}">{% trans 'Courses' %}</a></li>
            <li><a href="{% url 'blog:portfolios' %}">{% trans 'About us' %}</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'blog:register' %}">Sign up</a></li>
            <li><a href="{% url 'blog:login-page' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    <div>
        {% if user.is_authenticated %}
            <div class="dropdown">
                <button class="dropbtn">{{request.user}}</button>
                <div class="dropdown-content">
                    {% if user.is_staff %}
                        <a href="{% url 'student:my-courses' request.user %}">My courses</a>
                        <a href="{% url 'blog:profile' request.user.id %}">My profile</a>
                        <a href="{% url 'blog:portfolio' request.user.id %}">My portfolio</a>
                    {% else %}
                        <a href="{% url 'student:my-courses' request.user %}">My courses</a>
                        <a href="{% url 'blog:profile' request.user.id %}">My profile</a>
                    {% endif %}
                    <a href="{% url 'blog:logout' %}">Logout</a>
                </div>
            </div>
        {% endif %}
    </div>
    <div>
    </div>
    <div class="languages" style="display:none;">
        <form id="set-language" action="{% url 'set_language' %}" method="POST">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <select id="language-selection" name="language" onchange='changeLanguage(this.value, "{% url 'set_language' %}")'>
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{language.code}}" {% if language.code == LANGUAGE_CODE %} selected {% endif %} style="background-color:#0C0D13; color:#00AEFF; border:2px solid #00AEFF;">
                        ({{language.code}})
                    </option>
                {% endfor %}
            </select>
        </form>
        <div id="content-hidden"></div>
    </div>
</header>
<nav class="links-burguer">
   <input type="checkbox" id="menu_toggle">
   <label for="menu_toggle" class="menu_btn"><span></span></label>
   <ul class="menu-box">
       <li><a href="{% url 'blog:index' %}">{% trans 'Home' %}</a></li>
       <li><a href="{% url 'courses:index_course' %}">{% trans 'Courses' %}</a></li>
       <li><a href="{% url 'blog:portfolios' %}">{% trans 'About us' %}</a></li>
       {% if user.is_authenticated %}
       <li>
         <div class="dropdown">
           <button class="dropbtn">{{request.user}}</button>
           <div class="dropdown-content">

             {% if user.is_staff %}
                <a href="{% url 'student:my-courses' request.user %}">My courses</a>
                <a href="{% url 'blog:profile' request.user.id %}">My profile</a>
                <a href="{% url 'blog:portfolio' request.user.id %}">My portfolio</a>
             {% else %}
                <a href="{% url 'student:my-courses' request.user %}">My courses</a>
                <a href="{% url 'blog:profile' request.user.id %}">My profile</a>
             {% endif %}
                <a href="{% url 'blog:logout' %}">Logout</a>
           </div>
         </div>
       </li>
       {% else %}
       <li><a href="{% url 'blog:register' %}">Sign up</a></li>
       <li><a href="{% url 'blog:login-page' %}">Login</a></li>
       {% endif %}
   </ul>
</nav>
<span class="space-menu"></span>
<script src="{% static 'blog/js/languages.js' %}"></script>

skynet118/blog/templates/blog/particles.html
{% load static %}
<div class="particles-section">
    <div id="particles-js">
    </div>
</div>
<script src="{% static "blog/particles.js" %}"></script> 
<script src="{% static "blog/js/app.js" %}"></script>

skynet118/blog/templates/blog/password_reset_complete.html
{% extends "blog/base.html" %}
{% load i18n %}
{% block title-header %}Password reset complete{% endblock title-header %}
{% block content %}
<div class="reset_complete">
    <p>{% translate "Your password has been set.  You may go ahead and log in now." %}</p>
    <p><a href="{% url 'blog:login-page' %}">{% translate 'Log in' %}</a></p>
</div>
{% endblock %}

skynet118/blog/templates/blog/password_reset_form.html
{% extends "blog/base.html" %}
{% load i18n static %}
{% block title-header %}Password reset{% endblock title-header %}
{% block content %}


<section class="reset-password">
    <p>{% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>
    <form method="post">{% csrf_token %}
        <fieldset>
            <legend>Reset password</legend>
            <div class="form-row field-email">
                {{ form.email.errors }}
                <label for="id_email">{% translate 'Email address:' %}</label>
                {{ form.email }}
                <input id="buttonReset" type="submit" value="{% translate 'Reset my password' %}">
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

skynet118/blog/templates/blog/portfolio.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
{% load i18n %} 
<section class="about-me">
    <h1>My Portfolio</h1>
    {% if request.user.id == portfolio.user.id %}
        <a href="{% url 'blog:portfolio-update' pk=portfolio.id %}">Edit portfolio</a>
    {% endif %}
    <fieldset>
        <legend>Personal Data</legend>
        <img class="img-portfolio" src="/images/{{portfolio.image}}" alt="">
        <p>Profile: </p>
        <p>User: {{ portfolio.user }}</p>
        <p>Name: {{ portfolio.name }}</p>

        <p>Description: {{ portfolio.description }}</p>
    </fieldset>
    <fieldset>
        <legend>Description</legend>
        <p>Body: {{ portfolio.body|safe }}</p>
        <label for="">Skills:</label>
        <ul>
            {% for key, value in portfolio.skills.items %}
            <li>{{value}}</li>
            {% endfor %}
        </ul>
        <label for="">Is active?</label>
        <p>{{ portfolio.is_active }}</p>
    </fieldset>
</section>
{% endblock content %}

skynet118/blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
{% load i18n %} 
<section class="about-me">
    {% if request.user.id == profile.user.id %}
        <a href="{% url 'blog:profile-update' id=profile.id  %}">Update profile</a>
    {% endif %}
    <h1>My Profile</h1>
    <fieldset>
        <legend>Personal data</legend>
        <p>My avatar:</p>
        <img class="img-profile" src="/images/{{profile.avatar}}" alt="">
        <p>User name: {{ profile.user }}</p>
    </fieldset>

    <fieldset>
        <legend>About me</legend>
        <p>Title: {{ profile.title }}</p>
        <p>Mi bio: {{ profile.bio }}</p>
        <p>My cv: <a href="/images/{{profile.cv}}" download="{{profile.cv}}">Download</a></p>
    </fieldset>
</section>
{% endblock content %}

skynet118/blog/templates/blog/slides.html
{% load static %}
{% load i18n %}
<h2 class="courses-header">Courses</h2>
<p class="courses-paragraph">{% trans 'The courses are for all' %}</p>
<header class="courses">
    <div class="courses-available">
        {% for course in courses %}
            <div class="course course-{{course.pk }}">
                <div class="course-container">
                    <div class="course-logo">
                        <img src="{{ course.image.url }}" alt="{{ course.course_name }}"/>
                    </div>
                    <p class="course-name"><strong>Course: {{ course.course_name }}</strong></p>
                    <p class="age">{% trans 'Age' %}: {% trans 'from 12 year old' %}</p>
                    <a href="{% url "courses:index_course" %}">{% trans 'Read more' %}</a> 
                </div>
            </div>
        {% endfor %}
        <div class="buttons-change">
            <div class="arrow left-arrow">
                <svg width="24" height="90">
                    <line class="upper-side" x1="24" y1="0" x2="2" y2="46"></line>
                    <line class="lower-side" x1="2" y1="44" x2="24" y2="90"></line>
                </svg>
            </div>
            <div class="arrow right-arrow">
                <svg width="24" height="90">
                    <line class="upper-side" x1="0" y1="0" x2="22" y2="46"></line>
                    <line class="lower-side" x1="0" y1="90" x2="22" y2="44"></line>
                </svg>
            </div>
        </div>
    </div>
    <div class="navigation-auto">
        {% for course in courses %}
            <div id="radio-selection">
                <input type="radio" name="radio-btn" id="radio{{course.pk}}" value="{{course.pk}}">
            </div>
        {% endfor %}
    </div>
</header>
<script src="{% static 'blog/js/slices.js' %}"></script>