skynet118/blog/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

#include("blog")
app_name = 'blog'


urlpatterns = [
        # 
        path("register/", views.registerPage, name = "register"),
        path("login/", views.loginPage, name = "login-page"),
        path("logout/", views.logoutUser, name = "logout"),
        path(
            "password_reset/", 
            auth_views.PasswordResetView.as_view(
                template_name="blog/password_reset_form.html",
                email_template_name="blog/password_reset_email.html",
                subject_template_name="blog/password_reset_subject.txt",
                success_url = reverse_lazy('blog:password_reset_done') 
                ), 
            name = "password_reset"),

        path(
            "password_reset/done/",
            auth_views.PasswordResetDoneView.as_view(
                template_name="blog/password_reset_done.html"
                ),
            name = "password_reset_done"),

        path(
            "reset/<uidb64>/<token>/",
            auth_views.PasswordResetConfirmView.as_view(
                template_name="blog/password_reset_confirm.html",
                success_url = reverse_lazy('blog:password_reset_complete') 
                ),
            name = "password_reset_confirm"),
        path(
            "password_reset_complete/", 
            auth_views.PasswordResetCompleteView.as_view(
                template_name="blog/password_reset_complete.html"
                ), 
            name = "password_reset_complete"),

        path("restricted/", views.restricted_view, name = "restricted"),

        path("", views.index, name = "index"),
        path("contact/", views.contact_view, name = "contact"),
        path("contacts/", views.contacts_view, name = "contacts"),
        path("contact_create/", views.contact_create, name = "contact-create"),
        path("client_contact/", views.client_contact_view, name = "client-contact"),

        path("profile_create/", views.profile_create, name = "profile-create"),
        path("profile/<int:id>", views.profile_view, name = "profile"),
        path("profile_update/<int:id>", views.profile_update, name = "profile-update"),

        path("portfolio_create/", views.portfolio_create, name = "portfolio-create"),
        path("portfolios/", views.portfolios_view, name = "portfolios"),
        path("portfolio/<int:id>", views.portfolio_view, name = "portfolio"),
        path("portfolio_update/<int:pk>", views.portfolio_update, name = "portfolio-update"),

        path("comment/", views.CommentView.as_view(), name = "comments"),
        path("comment/<slug:slug>", views.CommentDetailView.as_view(), name = "comment-detail"),
        ]

skynet118/courses/urls.py
from django.urls import path, include
from . import views

#include("blog")
app_name = 'courses'


urlpatterns = [
        path("", views.index, name = "index_course"),
        path("course_packages/<int:fk>", views.course_package_view, name = "course_packages"),
        path("course/<int:id>", views.course_view, name="course_view"),
        path("create_course/", views.create_course, name = "create_course"),
        path("update_course/<int:pk>", views.update_course, name = "update_course"),
        path("delete_course/<int:pk>", views.delete_course, name = "delete_course"),
        #path("delete/", views.create_course, name = "create"),
        path("create_package/", views.create_package, name = "create_package"),
        path("update_package/<str:pk>", views.update_package, name = "update_package"),
        path("delete_package/<str:pk>", views.delete_package, name = "delete_package"),
    ]

skynet118/payments/urls.py
from django.urls import path, include

from . import views

app_name = "payments"

urlpatterns = [
        path("checkout/<int:pk>/<str:name>/", views.checkout, name="checkout"),
        path("checkout-trial/<int:id>/", views.checkout_trial, name="checkout-trial"),
        path("success/<str:name>/<str:idpay>", views.payment_complete,  name="success"),
        path("cart/", views.cart,  name="cart"),
        ]

skynet118/skynet118/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
        path('i18n/', include('django.conf.urls.i18n')),
        path('admin/', admin.site.urls),
        path('ckdeditor/', include('ckeditor_uploader.urls')),

        #path('', include('frontend.urls')),
        path('', include("blog.urls")),
        path('student/', include("student.urls")),
        path('payments/', include("payments.urls")),
        path('courses/', include("courses.urls")),
        ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skynet118/payments/models.py
from django.db import models
from blog.models import UserProfile
from courses.models import Course, Package

# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(UserProfile, max_length=200, null=True, blank=True, on_delete = models.CASCADE)
    course_name = models.ForeignKey(Course, max_length=200, null=True, blank=True, on_delete = models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transanction_id = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return str(self.id)

    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    package = models.ForeignKey(Package, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class Purchase(models.Model):
    purchase_id = models.CharField(primary_key=True, max_length=100)
    state = models.CharField(max_length=100)
    cod_state = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    package = models.CharField(max_length=100, blank=True)
    total = models.DecimalField(max_digits=5, decimal_places=2)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name

skynet118/payments/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from .models import Order, Course, Package, Purchase
import json, os, sys 
#from django.template import loader

from django.urls import reverse
from django.views import generic
from django.utils import timezone

#from paypalcheckoutsdk

from paypalpayoutssdk.core import PayPalHttpClient, SandboxEnvironment
from paypalcheckoutsdk.orders import OrdersGetRequest, OrdersCaptureRequest

# Create your views here.
def checkout_trial(request, id):
    customer = request.user
    course_trial = Course.objects.filter(id=id)[0]
    print(course_trial)
    if(request.method == "POST"):
        data = json.loads(request.body)
        order_id = data['orderID']
        details = GetOrder().get_order(order_id)
        detail_price = float(details.result.pruchase_units[0].amount.value)
        if(detail_price == float(course_trial.price)):
            transaction = CaptureOrder().capture_order(order_id, debug=True)
            purchase = Purchase(
                    purchase_id = transaction.result.id,
                    state = transaction.result.status,
                    cod_state = transaction.status_code,
                    course = f"course_trial.course_name",
                    total = transaction.result.purchase_unit[0].payments.captures[0].amount.value,
                    name = transaction.result.payer.name.given_name,
                    surname = transaction.result.payer.name.surname,
                    email = transaction.result.purchase_units[0].shipping.address.address_line_1,
                    )
            purchase.save()
            data = {
                    "id": f"{transaction.result.id}",
                    "name": f"{transaction.result.payer.name.given_name}"
                    }
            return JsonResponse(data)
        else:
            data = {
                    "name": "error",
                    "message": "We could not finish your purchase"
                    }
            return JsonResponse(data)

    context = {'course_trial': course_trial, 'customer': customer}
    return render(request, 'payments/checkout_trial.html', context)



def checkout(request, pk, name):
    customer = request.user 
    course = Course.objects.get(id=pk)
    package = Package.objects.filter(course_package=pk, package_name=name)[0]

    if(request.method == "POST"):
        package = Package.objects.filter(course_package=pk, package_name=name)[0]
        data = json.loads(request.body)
        order_id = data['orderID']
        details = GetOrder().get_order(order_id)
        detail_price = float(details.result.purchase_units[0].amount.value)
        if(detail_price == float(package.price)):
            trans = CaptureOrder().capture_order(order_id, debug=True)
            purchase = Purchase(
                    purchase_id = trans.result.id,
                    state = trans.result.status,
                    cod_state = trans.status_code,
                    course = f"{course.course_name}",
                    package = f"{package.package_name}",
                    total = trans.result.purchase_units[0].payments.captures[0].amount.value,
                    name = trans.result.payer.name.given_name,
                    surname = trans.result.payer.name.surname,
                    email = trans.result.payer.email_address,
                    address = trans.result.purchase_units[0].shipping.address.address_line_1,
                    )
            purchase.save()
            data = {
                "id": f"{trans.result.id}",
                "name": f"{trans.result.payer.name.given_name}"
            }
            #return HttpResponseRedirect(reverse('payments:success'))
            return JsonResponse(data)
        else:
            data = {
                "name": "error",
                "message": "We could not finish your purchase"
                    }
            return JsonResponse(data)

    context = {'package': package, 'course': course, 'customer': customer}
    return render(request, 'payments/checkout.html', context)

def cart(request):
    if(request.user.is_authenticated):
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items  = []
    context = {'items': items}
    return render(request, 'payments/cart.html', context)

def payment_complete(request, name, idpay):
    purchase = Purchase.objects.get(purchase_id=idpay)
    context = {
            "purchase": purchase
                }
    return render(request, 'payments/payment_complete.html', context)


class PayPalClient:

    def __init__(self):
        #self.client_id =  os.environ["PAYPAL-CLIENT-ID"] if 'PAYPAL-CLIENT-ID' in os.environ else "AWw0wNEoQtKQsAlFgFUjx59Qs7CZSCujq01Ml-cysbffLlvHpFHPcqg1lKNRO5SffFKszQeZVqQ56G77"
        self.client_id =  os.environ["PAYPAL-CLIENT-ID"] if 'PAYPAL-CLIENT-ID' in os.environ else "AWw0wNEoQtKQsAlFgFUjx59Qs7CZSCujq01Ml-cysbffLlvHpFHPcqg1lKNRO5SffFKszQeZVqQ56G77"
        #self.client_secret = os.environ["PAYPAL-CLIENT-SECRET"] if 'PAYPAL_CLIENT_SECRET' in os.environ else "EMfOdmE60zetRvaOR5GesXeFnLgMQ5SzVo4A-FSRDOCmzMZ0DWlrOSRsqs601W3sp0hW-1xIAkA6KxBR"
        self.client_secret = os.environ["PAYPAL-CLIENT-SECRET"] if 'PAYPAL_CLIENT_SECRET' in os.environ else "EMfOdmE60zetRvaOR5GesXeFnLgMQ5SzVo4A-FSRDOCmzMZ0DWlrOSRsqs601W3sp0hW-1xIAkA6KxBR"

        """Set up and return PayPal Python SDK environment with PayPal Access credentials.
           This sample uses SandboxEnvironment. In production, use
           LiveEnvironment."""

        self.environment = SandboxEnvironment(client_id=self.client_id, client_secret=self.client_secret)
        """ Returns PayPal HTTP client instance in an environment with access credentials. Use this instance to invoke PayPal APIs, provided the

            credentials have access. """
        self.client = PayPalHttpClient(self.environment)
    def object_to_json(self, json_data):
        """
	        Function to print all json data in an organized readable manner
	    """
        result = {}
        if(sys.version_info[0] < 3):
            itr = json_data.__dict__.iteritems()
        else:
            itr = json_data.__dict__.items()

        for key,value in itr:	
	        # Skip internal attributes.
            if(key.startswith("__")):
	            continue
            result[key] = self.array_to_json_array(value) if isinstance(value, list) else self.object_to_json(value) if not self.is_primittive(value) else value
	
        return result;
	
    def array_to_json_array(self, json_array):
        result =[]
        if(isinstance(json_array, list)):
            for item in json_array:
                result.append(self.object_to_json(item) if  not self.is_primittive(item) \
                              else self.array_to_json_array(item) if isinstance(item, list) else item)
	
        return result;
	
    def is_primittive(self, data):
        return isinstance(data, str) or isinstance(data, unicode) or isinstance(data, int)


class GetOrder(PayPalClient):
  """You can use this function to retrieve an order by passing order ID as an argument"""   

  def get_order(self, order_id):
    """Method to get order"""
    request = OrdersGetRequest(order_id)

    #3. Call PayPal to get the transaction
    response = self.client.execute(request)
    return response
    #4. Save the transaction in your database. Implement logic to save transaction to your database for future reference.


class CaptureOrder(PayPalClient):
  #2. Set up your server to receive a call from the client
  """this sample function performs payment capture on the order.
  Approved order ID should be passed as an argument to this function"""

  def capture_order(self, order_id, debug=False):
    """Method to capture order using order_id"""
    request = OrdersCaptureRequest(order_id)
    #3. Call PayPal to capture an order
    response = self.client.execute(request)
    #4. Save the capture ID to your database. Implement logic to save capture to your database for future reference.
    if(debug):
      print('Status Code: ', response.status_code)
      print('Status: ', response.result.status)
      print('Order ID: ', response.result.id)
      print('Links: ')
      for link in response.result.links:
          print('\t{}: {}\tCall Type: {}'.format(link.rel, link.href, link.method))
          print('Capture Ids: ')

      for purchase_unit in response.result.purchase_units:
          for capture in purchase_unit.payments.captures:
              print('\t', capture.id)
    return response

skynet118/payments/templates/payments/base_payment.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="UTF-8">
  <title>Skynet118</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv='X-UA-Compatible' content='IE-edge'> 
  <link rel="stylesheet" type= "text/css" href="{% static "payments/style_payments.css" %}">
  <link rel="stylesheet" type= "text/css" href="{% static "payments/media.css" %}">
  <link rel="stylesheet" type= "text/css" href="{% static "blog/style.css" %}">
  <link rel="stylesheet" type= "text/css" href="{% static "blog/media.css" %}">
  <link rel="icon" type="image/gif" href="{% static "blog/images/favicon.ico" %}">
  </head>
<body>
    {% include "blog/menu_var.html" %}
    {% block payment_content %}

    {% endblock payment_content %}

    {% include "blog/footer.html" %}

    <script type="text/javascript" src="{% static 'payments/js/cart.js' %}"></script>
</body>
</html>

skynet118/payments/templates/payments/cart.html
{% extends 'payments/base_payment.html' %}
{% block payment_content %}
    <section class="cart-details">
        <table>
            <tr>
                <th></th>
            </tr>
            <tr>
                {% for item in items %}
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.product.quantity }}</td>
                    <td>{{ item.product.get_total }}</td>
                {% endfor %}
            </tr>
        </table>
    </section>
{% endblock payment_content %}

skynet118/payments/templates/payments/checkout.html
{% extends 'payments/base_payment.html' %}
{% load static %}
{% block payment_content %}
	<a class="go-pricing" href="{% url 'courses:index_course' %}">Come back to Courses</a>
    <hr>
	<div class="wise">
		<h3 class="wise-text">If you want to pay using Wise, please use this link.</h3>
		<a href="https://wise.com/invite/u/nicolass337" target="_blank">Go to Wise</a>
		<div class="bank-accounts">
			<h3>Also you can do it using the following accounts:</h3>
			<label for="banks">Select an account</label>
			<select id="bank-account" name="banks" onchange="changeAccount(this.value)">
				<option disabled selected value>Select an option</option>
				<option value="usa">USA</option>
				<option value="canada">CANADA</option>
				<option value="europe">EU</option>
			</select>
			<div id="info-account"></div>
		</div>
	</div>
	<div class="container-products">
        <h3>Or use Paypal to make your payment</h3>
       <div class="img-product">
	      <img src="{{ course.image.url }}" alt="{{course.course_name}}">
       </div>
       <div class="purchase-info">
          <h3>{{ course.course_name }} course</h3>
		  <p>Number of lessons: {{package.nro_lessons}}</p>
		  <p>You are buying a <strong>{{package.package_name}}</strong> package</p>
          <h4 class="product-price" >Total: ${{package.price}} </h4>
          <div id="paypal-button-container"></div>
       </div>
    </div>
	<script src="{% static 'payments/js/accounts.js' %}"></script>
    <script src="https://www.paypal.com/sdk/js?client-id=AWw0wNEoQtKQsAlFgFUjx59Qs7CZSCujq01Ml-cysbffLlvHpFHPcqg1lKNRO5SffFKszQeZVqQ56G77&currency=USD"></script>
    <script>
        function getCookie(name){
            let cookieValue = null;
        	if (document.cookie && document.cookie !== '') {
            	const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
        			}
            	}
        	}
        	return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        let total = '{{package.price}}'
        let course_id = '{{course.id}}'

        paypal.Buttons({
            style: {
                shape: 'rect',
                color: 'blue',
                layout: 'vertical',
                label: 'buynow',
            },
            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: total 
                        }
                    }]
                });
            },
            // Finalize the transaction
            onApprove: function(data) {
                return fetch('/payments/checkout/{{course.id}}/{{package.package_name}}/', 
                {
                method: 'POST',
                headers: {'content-type': 'application/json', 'X-CSRFToken':csrftoken},
                body: JSON.stringify({orderID: data.orderID })
                }).then(response =>{

                    if(!response.ok){
                        throw new Error('There was an error');
                    }
                    return response.json();
                }).then(details =>{
                    window.location.replace(`/payments/success/${details.name}/${details.id}`)

                }).catch((error) => {
                    window.location.replace(`/payments/error/`)
                    console.log("Error:", error)
                })
             }
            //onApprove: function(data, actions) {
            //    return actions.order.capture().then(function(orderData) {
            //        // Successful capture! For demo purposes:
            //        console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
            //        var transaction = orderData.purchase_units[0].payments.captures[0];
            //        complete_order()
            //        alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
            //        // Replace the above to show a success message within this page, e.g.
            //        // const element = document.getElementById('paypal-button-container');
            //        // element.innerHTML = '';
            //        // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            //        // Or go to another URL:  actions.redirect('thank_you.html');
            //    });
            //}
        }).render('#paypal-button-container');
    </script>
{% endblock payment_content %}

skynet118/payments/templates/payments/checkout_trial.html
{% extends 'payments/base_payment.html' %}
{% load static %}
{% block payment_content %}
	<a class="go-pricing" href="{% url 'courses:index_course' %}">Come back to Courses</a>
    <hr>
	<div class="wise">
		<h3 class="wise-text">If you want to pay using Wise, please use this link.</h3>
		<a href="https://wise.com/invite/u/nicolass337" target="_blank">Go to Wise</a>
		<div class="bank-accounts">
			<h3>Also you can do it using the following accounts:</h3>
			<label for="banks">Select an account</label>
			<select id="bank-account" name="banks" onchange="changeAccount(this.value)">
				<option disabled selected value>Select an option</option>
				<option value="usa">USA</option>
				<option value="canada">CANADA</option>
				<option value="europe">EU</option>
			</select>
			<div id="info-account"></div>
		</div>
	</div>
	<div class="container-products">
        <h3>Or use Paypal to make your payment</h3>
       <div class="img-product">
	      <img src="{{ course_trial.image.url }}" alt="{{course_trial.course_name}}">
       </div>
       <div class="purchase-info">
          <h3>{{ course_trial.course_name }} course</h3>
          <p>You are buying a trial lesson of {{course_trial.course_name}}</p>
          <h4 class="product-price" >Total: ${{course_trial.price}} </h4>
          <div id="paypal-button-container"></div>
       </div>
    </div>
	<script src="{% static 'payments/js/accounts.js' %}"></script>
    <script src="https://www.paypal.com/sdk/js?client-id=AWw0wNEoQtKQsAlFgFUjx59Qs7CZSCujq01Ml-cysbffLlvHpFHPcqg1lKNRO5SffFKszQeZVqQ56G77&currency=USD"></script>
    <script>
        function getCookie(name){
            let cookieValue = null;
        	if (document.cookie && document.cookie !== '') {
            	const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
        			}
            	}
        	}
        	return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        let total = '{{course_trial.price}}'
        let course_id = '{{course_trial.id}}'

        paypal.Buttons({
            style: {
                shape: 'rect',
                color: 'blue',
                layout: 'vertical',
                label: 'buynow',
            },
            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: total 
                        }
                    }]
                });
            },
            // Finalize the transaction
            onApprove: function(data) {
                return fetch('/payments/checkout/{{course_trial.course_name}}/', 
                {
                method: 'POST',
                headers: {'content-type': 'application/json', 'X-CSRFToken':csrftoken},
                body: JSON.stringify({orderID: data.orderID })
                }).then(response =>{

                    if(!response.ok){
                        throw new Error('There was an error');
                    }
                    return response.json();
                }).then(details =>{
                    window.location.replace(`/payments/success/${details.name}/${details.id}`)

                }).catch((error) => {
                    window.location.replace(`/payments/error/`)
                    console.log("Error:", error)
                })
             }
            //onApprove: function(data, actions) {
            //    return actions.order.capture().then(function(orderData) {
            //        // Successful capture! For demo purposes:
            //        console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
            //        var transaction = orderData.purchase_units[0].payments.captures[0];
            //        complete_order()
            //        alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
            //        // Replace the above to show a success message within this page, e.g.
            //        // const element = document.getElementById('paypal-button-container');
            //        // element.innerHTML = '';
            //        // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            //        // Or go to another URL:  actions.redirect('thank_you.html');
            //    });
            //}
        }).render('#paypal-button-container');
    </script>
{% endblock payment_content %}

skynet118/payments/templates/payments/index_payment.html
{% extends "payments/base_payment.html" %}
{% block payment_content %}

	<div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AYASl9P_R7zkf7_8CvAbogrknfaOJlpnlkHZLAmxp5ArQF_BcML5fRE3d64Kmkvm-Nj1Ql2zPlIdcWXy&currency=RUB"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({
			style: {
				color: 'blue',
				shape: 'pill',
				label: 'pay',
				height: 42
			},

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '88.44'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];
                    alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                    // Replace the above to show a success message within this page, e.g.
                    // const element = document.getElementById('paypal-button-container');
                    // element.innerHTML = '';
                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                    // Or go to another URL:  actions.redirect('thank_you.html');
                });
            }


        }).render('#paypal-button-container');
    </script>
{% endblock payment_content %}

skynet118/payments/templates/payments/payment_complete.html
{% extends 'payments/base_payment.html' %}
{% block payment_content %}
{% load static %}
<section class="payment_details">
    <img src="{% static 'payments/images/payment_successful.png' %}" alt="">
    <h1>Your payment was successful</h1>
    <fieldset>
        <legend><h2>Details</h2></legend>
        <section>
            <p>Hello, {{purchase.name}}, the details of your purchase:</p>
        </section>
        <section>
            <p><strong>Purchase id: </strong>{{purchase.purchase_id}}</p>
        </section>
        <section>
            <p><strong>Code state: </strong>{{purchase.cod_state}}</p>
        </section>   
        <section>
            <p><strong>Course: </strong>{{purchase.course}}</p>
        </section>    
        <section>
            <p><strong>Package: </strong>{{purchase.package}}</p>
        </section>    
        <section>
            <label for=""></label>
            <p><strong>Total: </strong>${{purchase.total}}</p>
        </section>    
        <section>
            <p><strong>State: </strong>{{purchase.state}}</p>
        </section>   
        <section>
            {% if not user.is_authenticated %}
                <p>Login to start learning 
                <a href="{% url 'blog:login-page' %}"><strong>here</strong></a> 
                or if you don't have an account, create one 
                <a href="{% url 'blog:register' %}"><strong>here</strong></a></p>
            {% else %}
                <a href="{% url 'blog:index' %}">Go Home</a>
            {% endif %}
            <p>** Do not show to anyone your purchase id</p>
        </section>
    </fieldset>
</section>
{% endblock payment_content %}

skynet118/payments/templates/payments/store.html
{% extends 'payments/base_payment.html' %}
{% block payment_content %}
<div class="all-products">
    {% for course in courses %}
    <div class="container-products">
    	<div class="img-product img-list">
    		<img src={{ course.image.url }} alt="{{course.course_name}}">
    	</div>
		<h3>{{ course.course_name}}</h3>
        <p class="product-description">{{course.description}}</p>
		<p>Number of lessons: {{course.nro_lessons}}</p>
		<p>Number of tests: {{course.nro_tests}}</p>
		<p>Published: {{course.date_pub}}</p>
        <h4 class="product-price">${{course.price}}</h4>
        <a href="{% url 'payments:checkout' course.id %}" class="button-price">Buy Now!</a>
    </div>
  {% endfor %}
</div>
{% endblock payment_content %}